### ISSUE TITLE
Email address gets hyphenated.

### ISSUE THREAD

**Issue by dcons** [driesbenoit/ugent-letter#1]
Email address gets hyphenated.

<img width="387" alt="screenshot 2019-01-14 at 09 48 18" src="https://user-images.githubusercontent.com/7952751/51104511-9e769800-17e6-11e9-813a-e26279e69781.png">

Suggest correcting line 125 of the cls file to

            \begin{minipage}[b][25mm][t]{\leftcol} % corrected DC

instead of \rightcol

**Comment by driesbenoit** [comment]
There is an option "rightcolwidth" that can be set to adjust the width of the right column. The value defaults to 0.25, but can be increased in case of, e.g. longer email addresses or department names. For example:
`\documentclass[faculty=eb,rightcolwidth=.3]{ugent-letter}`

Also see the [readme file](https://github.com/driesbenoit/ugent-letter/blob/master/README.md) where the class options are discussed .

Does this solve your issue?

**Comment by dcons** [comment]
Yes, thank you!
